// ==UserScript==
// @name        SSPreviewer
// @namespace   11powder
// @author      pejuta
// @description 七海で色々なプレビューを表示する
// @include     /^http://www\.sssloxia\.jp/d/.*?(?:\.aspx)(?:\?.+)?$/
// @require     https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js
// @require     http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
// @resource    CSS_STYLE http://pjtool.webcrow.jp/ss/scripts/SSPreviewer/src/css/style.css
// @version     0.2.006
// @grant       GM_addStyle
// @grant       GM_getResourceText
// ==/UserScript==
var __extends=(this&&this.__extends)||function(f,a){for(var e in a){if(a.hasOwnProperty(e)){f[e]=a[e];}}function c(){this.constructor=f;}f.prototype=a===null?Object.create(a):(c.prototype=a.prototype,new c());
};define("lib/ss/profile",["require","exports"],function(c,a){var b=(function(){function d(e){if(e){this.iconURLArray=e.iconURLArray;this.nickname=e.nickname;
this.nameColor=e.nameColor;}else{this.iconURLArray=d.LoadIconURLArray();this.nickname=d.LoadNickname();this.nameColor=d.LoadNameColor();}}d.prototype.SaveIconURLArray=function(e){if(e!==undefined){this.iconURLArray=e;
}d.SaveIconURLArray(this.iconURLArray);return this;};d.prototype.SaveNickname=function(e){if(e!==undefined){this.nickname=e;}d.SaveNickname(this.nickname);
return this;};d.prototype.SaveNameColor=function(e){if(e!==undefined){this.nameColor=e;}d.SaveNameColor(this.nickname);return this;};d.LoadIconURLArray=function(){var e=localStorage.getItem("SSPreview_IconURLArray");
if(e===null){return[];}return JSON.parse(e);};d.SaveIconURLArray=function(e){localStorage.setItem("SSPreview_IconURLArray",JSON.stringify(e));};d.LoadNickname=function(){var e=localStorage.getItem("SSPreview_Nickname");
if(e===null){return"(名称)";}return e;};d.SaveNickname=function(e){localStorage.setItem("SSPreview_Nickname",e);};d.LoadNameColor=function(){var e=localStorage.getItem("SSPreview_NameColor");
if(e===null){return"";}return e;};d.SaveNameColor=function(e){localStorage.setItem("SSPreview_NameColor",e);};return d;}());a.Profile=b;});define("lib/ss/page",["require","exports"],function(b,a){var c=(function(){function e(f,g){this.profile=f;
this.initializer=g;}e.prototype.Init=function(f){this.initializer(f);};Object.defineProperty(e.prototype,"Settings",{get:function(){return this.profile;
},enumerable:true,configurable:true});Object.defineProperty(e.prototype,"Initializer",{get:function(){return this.initializer;},enumerable:true,configurable:true});
return e;}());a.Page=c;var d=(function(){function e(){}Object.defineProperty(e,"pathnameToPage",{get:function(){return{"/d/mainaction.aspx":e.MainPage,"/d/pbbs.aspx":e.PartyBBS,"/d/tradeaction.aspx":e.Trade,"/d/strgsaction.aspx":e.Reinforcement,"/d/battle.aspx":e.BattleSettings,"/d/battleprc.aspx":e.BattleSettings,"/d/battlespc.aspx":e.BattleSettings,"/d/battlemessage.aspx":e.BattleWords,"/d/battlemessageprc.aspx":e.BattleWords,"/d/battlemessagespc.aspx":e.BattleWords,"/d/bms.aspx":e.BattleWords,"/d/messageaction.aspx":e.Message,"/d/commesaction.aspx":e.GroupMessage,"/d/messagelog.aspx":e.MessageLog,"/d/commeslog.aspx":e.MessageLog,"/d/chara.aspx":e.CharacterSettings,"/d/com.aspx":e.Community,};
},enumerable:true,configurable:true});e.RunInitializer=function(g,f){if(this.ForAllPages){this.ForAllPages.Init(g);}var h=f.pathname;if(e.pathnameToPage.hasOwnProperty(h)&&e.pathnameToPage[h]){e.pathnameToPage[h].Init(g);
}};return e;}());a.PageConfig=d;});define("lib/util/string/format",["require","exports"],function(b,a){function c(g,e){if(g===null||g===undefined){return g;
}var f=""+g;for(var d in e){if(e[d]===undefined&&e[d]===null){continue;}f=f.replace(new RegExp("{"+d+"}","g"),""+e[d]);}return f;}return c;});define("lib/util/string/replaceLoop",["require","exports"],function(b,a){function c(f,d,g){if(f===null||f===undefined){return f;
}var e=""+f;if(typeof d==="string"){for(;;){if(e.indexOf(d)===-1){return e;}e=e.replace(d,g);}}for(;;){if(!d.test(e)){return e;}e=e.replace(d,g);}}return c;
});define("lib/util/html/escape",["require","exports"],function(b,e){var g={"&":"&amp;","'":"&#x27;","`":"&#x60;",'"':"&quot;","<":"&lt;",">":"&gt;"};var i=new RegExp("["+Object.keys(g).join("")+"]","g");
function l(k,n,m){if(k===undefined||k===null){return k;}if(n===undefined||n===null){return k.replace(i,function(o){return g[o];});}return k.replace(new RegExp(n,m),function(o){return l(o);
});}e.escape=l;var a={};for(var d=0,j=Object.keys(g);d<j.length;d++){var c=j[d];a[g[c]]=c;}var h=new RegExp("(?:"+Object.keys(a).join("|")+")","g");function f(k,n,m){if(k===undefined||k===null){return k;
}if(n===undefined||n===null){return k.replace(h,function(o){return a[o];});}return k.replace(new RegExp(l(n),m),function(o){return f(o);});}e.unescape=f;
});define("lib/util/html/tag",["require","exports"],function(b,a){function c(d){return d.replace(/(?:\r\n|\r|\n)/g,"<BR>");}a.lineBreaksToBR=c;});define("lib/ss/expr/parser",["require","exports"],function(b,a){var c=(function(){function d(){}d.ParseAnd=function(e){var p=e.split(/((@@@|@((?![^<@]*\/\d+\/)[^<@]+)@)(?:\/(\d+)\/)?|\/(\d+)\/)/g);
var f={source:{text:p[0]},attr:{}};if(p.length===1){return[f];}var q=[];for(var i=0,l=p.length;i<l;i+=6){if(i===0){if(p[0]!==""){q.push(f);}continue;}var k=p.slice(i-5,i+1);
var n=k[1]==="@@@";var o=k[2];var g=void 0;if(k[3]!==void 0){g=k[3];}else{if(k[4]!==void 0){g=k[4];}}var r=k[5];var j=k[0];var m={stringMode:n,changedName:o,iconNumber:g};
var h={text:r,separator:j};q.push({source:h,attr:m});}return q;};d.ParseOr=function(g){var i=g.split("###");var h=[];for(var e=0,f=i.length;e<f;e++){h.push(d.ParseAnd(i[e]));
}return h;};return d;}());a.Parser=c;});define("lib/preview/model_formatter",["require","exports"],function(b,a){var c=(function(){function d(){}d.prototype.Exec=function(f,e){return f;
};return d;}());a.Formatter=c;});define("lib/ss/preview/templates",["require","exports"],function(b,a){a.diceTagTemplateHTML=null;a.cardTagTemplateHTML=null;
a.defaultTemplate=null;a.defaultSeparator=null;a.diary=null;a.diaryCharCountsHTML=null;a.message=null;a.partyBBS=null;a.serif=null;});define("lib/preview/config",["require","exports"],function(b,a){a.neverUpdateHTMLIfHidden=true;
a.previewDelay_ms=0;});define("lib/ss/preview/config",["require","exports","lib/ss/preview/templates","lib/preview/config"],function(b,a,c,d){a.Templates=c;
a.Preview=d;var e;(function(f){f.imgBaseURL=null;f.showsCharCountsOnDiary=true;f.randomizesDiceTagResult=false;f.randomizesCardTagResult=false;})(e=a.SSPreview||(a.SSPreview={}));
});define("lib/ss/preview/model_misc",["require","exports"],function(c,b){var f=(function(){function g(){}g.Throw=function(){return Math.floor(Math.random()*6)+1;
};return g;}());b.DiceCube=f;(function(g){g[g.Spade=0]="Spade";g[g.Heart=1]="Heart";g[g.Diamond=2]="Diamond";g[g.Clover=3]="Clover";g[g.Joker=4]="Joker";
})(b.CardSuits||(b.CardSuits={}));var e=b.CardSuits;var a=(function(){function g(h){this.num=0;this.suit=Math.floor(h/13);if(this.suit!==e.Joker){this.num=h%13+1;
}}Object.defineProperty(g.prototype,"Suit",{get:function(){return this.suit;},enumerable:true,configurable:true});Object.defineProperty(g.prototype,"Number",{get:function(){return this.num;
},enumerable:true,configurable:true});return g;}());b.Card=a;var d=(function(){function g(i,h){if(i===void 0){i=g._DEFAULT_JOKERS;}if(h===void 0){h=true;
}this.jokers=i;this.usesNewDeckOnOutOfCards=h;this.NewDeck();}Object.defineProperty(g.prototype,"ExtantCards",{get:function(){return this._cards.concat();
},enumerable:true,configurable:true});Object.defineProperty(g.prototype,"length",{get:function(){return this._cards.length;},enumerable:true,configurable:true});
Object.defineProperty(g.prototype,"InitialLength",{get:function(){return 52+this.jokers;},enumerable:true,configurable:true});g.prototype.NewDeck=function(j){if(j===void 0){j=true;
}var k=[];var i=this.InitialLength;for(var h=0;h<i;++h){k[h]=new a(h);}this._cards=k;if(j){this.Shuffle();}return this;};g.prototype.Shuffle=function(){var k=this._cards;
var i=k.length;while(i>0){var j=Math.floor(Math.random()*i--);h=[k[j],k[i]],k[i]=h[0],k[j]=h[1];}return this;var h;};g.prototype.Draw=function(){if(this._cards.length>0){return this._cards.pop();
}if(this.usesNewDeckOnOutOfCards){this.NewDeck();return this.Draw();}return null;};g._DEFAULT_JOKERS=1;return g;}());b.CardsDeck=d;});define("lib/ss/preview/model_formatter",["require","exports","lib/util/string/format","lib/util/string/replaceLoop","lib/util/html/escape","lib/util/html/tag","lib/ss/expr/parser","lib/ss/preview/config","lib/ss/preview/model_misc"],function(b,d,g,h,j,i,f,a,k){var e=(function(){function l(){}l.removeIndents=function(m){return m.replace(/^[\t ]+/gm,"");
};l.removeLineBreaks=function(m){return m.replace(/\r\n|\r|\n/g,"");};l.Normalize=function(m){var o={};for(var p in m){var n=m[p];if(typeof n==="string"){o[p]=this.removeLineBreaks(this.removeIndents(n));
}}return o;};return l;}());var c=(function(){function l(m){this.Profile=m.profile;this.StringModeAsDefault=m.stringModeAsDefault||false;this.AllowsOrTag=m.allowsOrTag||false;
this.setIcon0AsDefaultWithNameTags=m.setIcon0AsDefaultWithNameTags||false;this.Template=m.template||a.Templates.defaultTemplate||l._DEFAULT_TEMPLATE;var n=a.Templates.defaultSeparator||l._DETAULT_SEPARATORS;
if(m.separators){this.Separators={and:(m.separators.and===void 0||m.separators.and===null)?n.and:m.separators.and,or:(m.separators.or===void 0||m.separators.or===null)?n.or:m.separators.or};
}else{this.Separators=n;}if(m.htmlEmptyOrBlock===void 0||m.htmlEmptyOrBlock===null){this.htmlEmptyOrBlock=l._DEFAULT_TEMPLATE.Body_WhenOrIsEmpty;}else{this.htmlEmptyOrBlock=m.htmlEmptyOrBlock;
}}Object.defineProperty(l.prototype,"Profile",{get:function(){return this.profile;},set:function(m){this.profile=m;},enumerable:true,configurable:true});
Object.defineProperty(l.prototype,"Template",{get:function(){return this.template;},set:function(m){this.template=e.Normalize(m);},enumerable:true,configurable:true});
Object.defineProperty(l.prototype,"Separators",{get:function(){return this.separators;},set:function(m){this.separators=e.Normalize(m);},enumerable:true,configurable:true});
Object.defineProperty(l.prototype,"StringModeAsDefault",{get:function(){return this.stringModeAsDefault;},set:function(m){this.stringModeAsDefault=m;},enumerable:true,configurable:true});
Object.defineProperty(l.prototype,"AllowsOrTag",{get:function(){return this.allowsOrTag;},set:function(m){this.allowsOrTag=m;},enumerable:true,configurable:true});
Object.defineProperty(l.prototype,"HTMLEmptyOrBlock",{get:function(){return this.htmlEmptyOrBlock;},set:function(m){this.htmlEmptyOrBlock=m;},enumerable:true,configurable:true});
l.prototype.Exec=function(o){var m=j.escape(o);m=h(m,l.reReplace_EscapedDecoTag,"<span class='$1'>$2</span>");m=this.Format(m);m=m.replace(l.reReplace_EscapedDiceTag,function(p){return l.GenerateDiceTag(a.SSPreview.randomizesDiceTagResult);
});var n=null;if(a.SSPreview.randomizesCardTagResult){n=new k.CardsDeck(1);}m=m.replace(l.reReplace_EscapedCardTag,function(p){return l.GenerateCardTag(n);
});m=i.lineBreaksToBR(m);m=j.unescape(m,"<BR>","g");return m;};l.prototype.Format=function(m){if(this.allowsOrTag){return this.FormatOrs(f.Parser.ParseOr(m));
}else{return this.FormatAnds(f.Parser.ParseAnd(m));}};l.prototype.FormatOrs=function(r){var m=[];for(var p=0,o=r.length;p<o;p++){var n=r[p];var q=n.length===1&&([n[0].source.separator,n[0].source.text].join("")==="");
if(q&&this.htmlEmptyOrBlock!==null){m.push(this.htmlEmptyOrBlock);}else{m.push(this.FormatAnds(r[p]));}}return m.join(this.separators.or);};l.prototype.FormatAnds=function(w){var m=[];
var y=l.DefaultIconURL();for(var v=0,s=w.length;v<s;v++){var q=w[v];var p=void 0;if(q.attr.stringMode===void 0){p=this.stringModeAsDefault;}else{if(this.stringModeAsDefault&&q.attr.changedName===void 0){p=true;
}else{p=q.attr.stringMode;}}var u=void 0;if(q.attr.changedName===void 0){u=this.profile.nickname;}else{u=q.attr.changedName;}var o=void 0;if(q.attr.iconNumber===void 0){o=-1;
}else{o=parseInt(q.attr.iconNumber);}var r=void 0;if(o===-1){if(this.setIcon0AsDefaultWithNameTags||!q.source.separator){r=this.profile.iconURLArray[0];
}}else{r=this.profile.iconURLArray[o];}if(!r){r=y;}var n=void 0;var A=void 0;if(p){n=q.source.text;A="";}else{var z=l.takeLineBreaksFromEnd(q.source.text);
n=z.text;A=z.breaks||"";}var x=void 0;if(p){if(o===-1){x=this.template.Body_StringMode;}else{x=this.template.Body_StringModeAndIcon;}}else{x=this.template.Body_WordsMode;
}m.push(g(x,{iconURL:r,name:u,nameColor:this.profile.nameColor,bodyHTML:n,endBreaks:A}));}return m.join(this.separators.and);};l.DefaultIconURL=function(){return((a.SSPreview.imgBaseURL||l._DEFAULT_IMG_BASE_URL)+"default.jpg");
};l.GenerateDiceTag=function(m){if(m===void 0){m=false;}var n=1;if(m){n=k.DiceCube.Throw();}return g(a.Templates.diceTagTemplateHTML||l._DEFAULT_DICE_TEMPLATE,{imgDir:a.SSPreview.imgBaseURL||l._DEFAULT_IMG_BASE_URL,resultNum:n});
};l.GenerateCardTag=function(m){var n;if(m){n=m.Draw();}else{n=new k.Card(0);}var o=l.SuitTexts[n.Suit];var p="";if(n.Suit!==k.CardSuits.Joker){p+=n.Number;
}return g(a.Templates.cardTagTemplateHTML||l._DEFAULT_CARD_TEMPLATE,{imgDir:a.SSPreview.imgBaseURL||l._DEFAULT_IMG_BASE_URL,suit:o,num:p});};l.takeLineBreaksFromEnd=function(p){var n=/\n+$/.exec(p);
if(!n){return{text:p};}var o=n[0];var q=p.slice(0,-(o.length));return{text:q,breaks:o};};l._DEFAULT_TEMPLATE={Body_WordsMode:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon" rowspan="2"><IMG border = 0 alt=Icon align=left src="{iconURL}" width=60 height=60></td><td class="Name"><font color="{nameColor}" class="B">{name}</font></td></tr><tr><td class="Words">\u300C{bodyHTML}\u300D{endBreaks}</td></tr></table>',Body_StringModeAndIcon:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon"><IMG border = 0 alt=Icon align=left src="{iconURL}" width=60 height=60></td><td class="String">{bodyHTML}</td></tr></table>',Body_StringMode:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon"/><td class="String">{bodyHTML}</td></tr></table>',Body_WhenOrIsEmpty:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon"/><td class="String"><span class=\'I\'>(\u8868\u793A\u306A\u3057)</span></td></tr></table>'};
l._DEFAULT_DICE_TEMPLATE='<img alt="dice" src="{imgDir}d{resultNum}.png" border="0" height="20" width="20">';l._DEFAULT_CARD_TEMPLATE='<IMG border=0 alt=card src="{imgDir}t/{suit}{num}.png" width=30 height=40>';
l._DEFAULT_IMG_BASE_URL="http://www.sssloxia.jp/p/";l._DETAULT_SEPARATORS={and:"",or:"<div class='separator_or'/>"};l.reReplace_EscapedDecoTag=new RegExp(j.escape("<(F[1-7]|B|I|S)>([\\s\\S]*?)</\\1>"),"g");
l.reReplace_EscapedDiceTag=new RegExp(j.escape("<D>"),"g");l.reReplace_EscapedCardTag=new RegExp(j.escape("<T>"),"g");l.SuitTexts=["sd","he","da","cv","j"];
return l;}());d.SSFormatter=c;});define("lib/interface/disposable",["require","exports"],function(b,a){});define("lib/util/timer/timer",["require","exports"],function(b,a){var c=(function(){function d(){this.date_start=0;
this.time_ms=0;this.resetTimeWhenStarting=false;}Object.defineProperty(d.prototype,"Time_ms",{get:function(){return this.time_ms+Date.now()-this.date_start;
},enumerable:true,configurable:true});Object.defineProperty(d.prototype,"isRunning",{get:function(){return !!this.date_start;},enumerable:true,configurable:true});
d.prototype.Start=function(){if(this.isRunning&&!this.resetTimeWhenStarting){return;}if(this.resetTimeWhenStarting){this.ResetTime();}this.date_start=Date.now();
return this;};d.prototype.Stop=function(){return this.Pause().ResetTime();};d.prototype.Pause=function(){if(!this.isRunning){return;}this.time_ms+=Date.now()-this.date_start;
this.date_start=0;return this;};d.prototype.ResetTime=function(){if(this.isRunning){this.date_start=Date.now();}else{this.date_start=0;}this.time_ms=0;
return this;};d.prototype.PrintTime=function(){console.log("time(ms): "+this.Time_ms);return this;};return d;}());return c;});define("lib/util/timer/timerEvent",["require","exports","lib/util/timer/timer"],function(b,a,c){var d=(function(e){__extends(f,e);
function f(g,h){e.call(this);this.afterPeriod=g;this.period_ms=h;this.id=0;}f.prototype.setCallbackArg=function(g){if(g===undefined){return;}this.callbackArg=g;
};f.prototype.Start=function(h){this.setCallbackArg(h);if(!this.isRunning){var g=this.period_ms-this.time_ms;if(g<0){g=0;}this.id=setTimeout(this.afterPeriod,g,h);
}e.prototype.Start.call(this);return this;};f.prototype.Stop=function(g,h){if(g===void 0){g=false;}if(g){this.setCallbackArg(h);this.afterPeriod((h===undefined?this.callbackArg:h));
}return this.Pause().ResetTime();};f.prototype.Pause=function(){if(!this.isRunning){return;}clearTimeout(this.id);this.id=0;e.prototype.Pause.call(this);
return this;};f.prototype.ResetTime=function(g){this.setCallbackArg(g);if(this.isRunning){clearTimeout(this.id);this.id=setTimeout(this.afterPeriod,this.period_ms,(g===undefined?this.callbackArg:g));
}e.prototype.ResetTime.call(this);return this;};f.prototype.Dispose=function(){this.Stop();};return f;}(c));return d;});define("lib/preview/model",["require","exports","jquery","lib/preview/model_formatter","lib/util/timer/timerEvent","lib/preview/config"],function(d,c,f,e,g,a){var b=(function(){function h(i,j){if(i===void 0){i=new e.Formatter();
}if(j===void 0){j=a.previewDelay_ms;}this.formatter=i;this.delay_ms=j;this.previewHTML=null;this.source=null;this.extraArg=null;this.isVisible=false;this.isDisabled=false;
this.$onUpdated=f.Callbacks("stopOnFalse");this.InitTimerEvent();}Object.defineProperty(h.prototype,"Formatter",{get:function(){return this.formatter;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"PreviewHTML",{get:function(){return this.previewHTML;},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"Delay_ms",{get:function(){return this.delay_ms;
},set:function(i){this.delay_ms=i;this.InitTimerEvent();},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"IsVisible",{get:function(){return this.isVisible;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"IsDisabled",{get:function(){return this.isDisabled;},enumerable:true,configurable:true});
h.prototype.ReserveUpdate=function(i){if(this.isDisabled){return false;}if(i.source===this.source&&JSON.stringify(i.extraArg)===JSON.stringify(this.extraArg)){return false;
}this.timerEvt.Start(i);return true;};h.prototype.InitTimerEvent=function(){var i=this;if(this.timerEvt){this.timerEvt.Dispose();}this.timerEvt=new g(function(j){i.Update(j);
},this.delay_ms);this.timerEvt.resetTimeWhenStarting=true;return this;};h.prototype.Update=function(i){this.InitOnUpdating().UpdateInfo(i);this.TriggerOnUpdatedEvent();
return this;};h.prototype.InitOnUpdating=function(){this.SetAsShown();return this;};h.prototype.UpdateInfo=function(i){if(this.isDisabled){return false;
}if(!this.isVisible&&a.neverUpdateHTMLIfHidden){return false;}this.source=i.source;this.extraArg=i.extraArg;this.previewHTML=this.formatter.Exec(i.source,i.extraArg);
return true;};h.prototype.Show=function(){this.SetAsShown();if(!this.previewHTML){return this;}this.TriggerOnUpdatedEvent();return this;};h.prototype.Hide=function(){this.SetAsHidden();
if(!this.previewHTML){return this;}this.TriggerOnUpdatedEvent();return this;};h.prototype.SetAsHidden=function(){this.isVisible=false;return this;};h.prototype.SetAsShown=function(){this.isVisible=true;
return this;};h.prototype.SetAsDisabled=function(){this.isDisabled=true;return this;};h.prototype.SetAsEnabled=function(){this.isDisabled=false;return this;
};h.prototype.TriggerOnUpdatedEvent=function(){this.$onUpdated.fire(this);return this;};h.prototype.onUpdated=function(i){if(i instanceof Array){this.$onUpdated.add(i);
}else{this.$onUpdated.add(i);}return this;};h.prototype.offUpdated=function(i){if(i instanceof Array){this.$onUpdated.remove(i);}else{this.$onUpdated.remove(i);
}return this;};h.prototype.Dispose=function(){this.timerEvt.Dispose();this.$onUpdated.disable();this.previewHTML=null;this.isDisabled=true;this.isVisible=false;
};return h;}());c.PreviewModel=b;});define("lib/ss/preview/model",["require","exports","lib/preview/model"],function(b,a,d){var c=(function(f){__extends(e,f);
function e(g,h){f.call(this,g,h);}Object.defineProperty(e.prototype,"Formatter",{get:function(){return this.formatter;},enumerable:true,configurable:true});
e.prototype.UpdateInfo=function(g){if(g.source===""){this.SetAsHidden();}return f.prototype.UpdateInfo.call(this,g);};return e;}(d.PreviewModel));a.SSPreviewModel=c;
});define("lib/ss/preview/partyBBS/model_formatter",["require","exports","lib/util/string/format","lib/ss/preview/model_formatter"],function(c,a,e,b){var d=(function(g){__extends(f,g);
function f(h){g.call(this,h);}f.prototype.Exec=function(k,j){if(j===void 0){j={title:"",name:""};}var h=g.prototype.Exec.call(this,k);if(j.title===""){j=Object.create(j);
j.title="無題";}var i=e(f.TEMPLATE_CONTAINER,j);return e(i,{html:h});};f.TEMPLATE_CONTAINER='<div class="BackBoard">\n    <b>xxx \uFF1A{title}</b> &nbsp;&nbsp;{name}&#12288;\uFF0820xx/xx/xx xx:xx:xx\uFF09 <br> <br>{html}<br><br><br clear="ALL">\n</div>';
return f;}(b.SSFormatter));a.PartyBBSFormatter=d;});define("lib/ss/preview/partyBBS/model",["require","exports","lib/ss/preview/model","lib/ss/preview/partyBBS/model_formatter","lib/ss/preview/templates"],function(d,c,f,b,e){var a=(function(h){__extends(g,h);
function g(i,j){h.call(this,new b.PartyBBSFormatter({profile:i,template:e.partyBBS,stringModeAsDefault:true}),j);}Object.defineProperty(g.prototype,"Formatter",{get:function(){return this.formatter;
},enumerable:true,configurable:true});g.prototype.ReserveUpdate=function(i){if(i.source===this.source&&i.extraArg.title===this.extraArg.title&&i.extraArg.name===this.extraArg.name){return false;
}return h.prototype.ReserveUpdate.call(this,i);};g.prototype.UpdateInfo=function(i){if(i.extraArg.name===""){this.SetAsHidden();}return h.prototype.UpdateInfo.call(this,i);
};return g;}(f.SSPreviewModel));c.PartyBBSModel=a;});define("lib/ss/preview/diary/model_formatter",["require","exports","lib/util/string/format","lib/ss/preview/model_formatter"],function(c,b,e,a){var d=(function(g){__extends(f,g);
function f(h){g.call(this,h);}f.prototype.Exec=function(i){var h=g.prototype.Exec.call(this,i);return e(f.TEMPLATE_CONTAINER,{html:h});};f.TEMPLATE_CONTAINER='<div name="Diary">{html}</div>';
return f;}(a.SSFormatter));b.DiaryFormatter=d;});define("lib/ss/expr/rule",["require","exports"],function(c,b){function a(e){var f=e.length-e.replace(/\n/g,"").length;
var d=e.length-f;return{charCount:d,lfCount:f};}b.CountExprChars=a;});define("lib/ss/preview/diary/model",["require","exports","lib/ss/preview/diary/model_formatter","lib/ss/preview/model","lib/ss/expr/rule","lib/ss/preview/config","lib/ss/preview/templates"],function(e,d,b,g,c,a,f){var h=(function(j){__extends(i,j);
function i(k){j.call(this,new b.DiaryFormatter({profile:k.profile,template:f.diary,stringModeAsDefault:true}),k.delay_ms);if("showsCharCounts" in k){this.showsCharCounts=k.showsCharCounts;
}else{this.showsCharCounts=a.SSPreview.showsCharCountsOnDiary||false;}}Object.defineProperty(i.prototype,"Formatter",{get:function(){return this.formatter;
},enumerable:true,configurable:true});Object.defineProperty(i.prototype,"ShowsCharCounts",{get:function(){return this.showsCharCounts;},enumerable:true,configurable:true});
Object.defineProperty(i.prototype,"CharCounts",{get:function(){return this.charCounts;},enumerable:true,configurable:true});i.prototype.UpdateInfo=function(k){this.charCounts=c.CountExprChars(k.source);
return j.prototype.UpdateInfo.call(this,k);};i.MAX_LENGTH_OF_CHARS=5000;i.MAX_COUNT_OF_LFS=2500;return i;}(g.SSPreviewModel));d.DiaryModel=h;});define("lib/ss/preview/serif/model",["require","exports","lib/ss/preview/model_formatter","lib/ss/preview/model","lib/ss/preview/templates"],function(c,a,f,b,d){var e=(function(g){__extends(h,g);
function h(i,j){g.call(this,new f.SSFormatter({profile:i,template:d.serif,allowsOrTag:true}),j);}return h;}(b.SSPreviewModel));a.SerifModel=e;});define("lib/ss/preview/message/model",["require","exports","lib/ss/preview/model_formatter","lib/ss/preview/model","lib/ss/preview/templates"],function(c,b,f,a,d){var e=(function(g){__extends(h,g);
function h(i,j){g.call(this,new f.SSFormatter({profile:i,template:d.message,allowsOrTag:true}),j);}return h;}(a.SSPreviewModel));b.MessageModel=e;});define("lib/ss/preview/model_formatters",["require","exports","lib/ss/preview/diary/model_formatter","lib/ss/preview/partyBBS/model_formatter","lib/ss/preview/model_formatter"],function(b,a,e,d,c){a.Diary=e.DiaryFormatter;
a.PartyBBS=d.PartyBBSFormatter;a.SSFormatter=c.SSFormatter;});define("lib/ss/preview/models",["require","exports","lib/ss/preview/partyBBS/model","lib/ss/preview/diary/model","lib/ss/preview/serif/model","lib/ss/preview/message/model"],function(d,c,b,a,f,e){c.PartyBBS=b.PartyBBSModel;
c.Diary=a.DiaryModel;c.Serif=f.SerifModel;c.Message=e.MessageModel;});define("lib/preview/view",["require","exports","jquery","lib/preview/config"],function(d,c,f,a){(function(g){g[g.InsertAfter=0]="InsertAfter";
g[g.InsertBefore=1]="InsertBefore";g[g.AppendTo=2]="AppendTo";g[g.PrependTo=3]="PrependTo";})(c.InsertWay||(c.InsertWay={}));var e=c.InsertWay;var b=(function(){function g(h){this.insert=h;
}Object.defineProperty(g.prototype,"PreviewContainer",{get:function(){return this.$container?this.$container[0]:null;},enumerable:true,configurable:true});
g.prototype.InsertContainer=function(){this.$container=f(g.containerHTML);switch(this.insert.way){case e.InsertAfter:this.$container.insertAfter(this.insert.target);
break;case e.InsertBefore:this.$container.insertBefore(this.insert.target);break;case e.AppendTo:this.$container.appendTo(this.insert.target);break;case e.PrependTo:this.$container.prependTo(this.insert.target);
break;default:throw new Error("InsertionMode指定エラー");}return this;};g.prototype.Hide=function(h){if(!this.$container){return;}this.$container.css("display","none");
return this;};g.prototype.Show=function(h){if(!this.$container){return;}this.$container.css("display","");return this;};g.prototype.Update=function(h){if(h.IsDisabled){return false;
}if(!this.$container){this.InsertContainer();}if(h.IsVisible){this.Show(h);}else{this.Hide(h);if(a.neverUpdateHTMLIfHidden){return false;}}this.$container.html(h.PreviewHTML);
return true;};g.prototype.Dispose=function(){this.$container.remove();};g.containerHTML='<div class="preview"/>';return g;}());c.PreviewView=b;});define("lib/ss/preview/diary/view",["require","exports","jquery","lib/util/string/format","lib/ss/preview/diary/model","lib/preview/view","lib/ss/preview/templates"],function(b,a,f,h,d,e,c){var g=(function(i){__extends(j,i);
function j(k){i.call(this,k);}j.BuildCharCountLine=function(m){var l=c.diaryCharCountsHTML||j._DEFAULT_TEMPLATE_CHARCOUNTS;l=h(l,{charCount:m.charCount,charCountMax:d.DiaryModel.MAX_LENGTH_OF_CHARS,lfCount:m.lfCount,lfCountMax:d.DiaryModel.MAX_COUNT_OF_LFS});
var k=f(l);if(m.charCount>d.DiaryModel.MAX_LENGTH_OF_CHARS){k.children("[name=charCount]").addClass("over");}if(m.lfCount>d.DiaryModel.MAX_COUNT_OF_LFS){k.children("[name=lfCount]").addClass("over");
}return k;};j.prototype.Update=function(k){if(!i.prototype.Update.call(this,k)){return false;}if(k.ShowsCharCounts){this.$container.prepend(j.BuildCharCountLine(k.CharCounts));
}return true;};j._DEFAULT_TEMPLATE_CHARCOUNTS='<p class="char_count_line"><span class="char_count_cnt"><span name="charCount" class="char_count">{charCount}</span> / {charCountMax}</span> <span class="lf_count_cnt">(\u6539\u884C: <span name="lfCount" class="lf_count">{lfCount}</span> / {lfCountMax})</span></p>';
return j;}(e.PreviewView));a.DiaryView=g;});define("lib/ss/preview/views",["require","exports","lib/ss/preview/diary/view","lib/preview/view"],function(b,a,d,c){a.Diary=d.DiaryView;
a.InsertWay=c.InsertWay;});define("lib/util/array/set",["require","exports"],function(b,a){var c=(function(){function d(e,f){if(e===void 0){e=function(h,g){return(h===g);
};}this.equalityValidator=e;if(f&&f instanceof Array){this.innerArray=f.concat();}else{this.innerArray=[];}}d.prototype.has=function(f){return this.indexOf(f)!==-1;
};d.prototype.indexOf=function(h){var i=this;var f;var g=this.innerArray.some(function(j,k,e){f=k;return i.equalityValidator(j,h);});if(g){return f;}else{return -1;
}};d.prototype.add=function(f){if(this.has(f)){return this;}this.innerArray.push(f);return this;};d.prototype.addAll=function(f){for(var h=0,g=f;h<g.length;
h++){var i=g[h];this.add(i);}return this;};d.prototype.del=function(g){var f=this.indexOf(g);if(f===-1){return false;}this.innerArray.splice(f,1);return true;
};d.prototype.delAll=function(g){var j=false;for(var i=0,h=g;i<h.length;i++){var k=h[i];j=this.del(k)||j;}return j;};d.prototype.clear=function(){this.innerArray=[];
};d.prototype.forEach=function(h){for(var g=0,f=this.innerArray;g<f.length;g++){var e=f[g];h(e,e,this);}};Object.defineProperty(d.prototype,"size",{get:function(){return this.innerArray.length;
},enumerable:true,configurable:true});d.prototype.toArray=function(){return this.innerArray.concat();};return d;}());return c;});define("lib/util/jquery/customEvent",["require","exports","lib/util/array/set","jquery"],function(c,b,d,e){function f(h,g){return h.target.is(g)&&h.eventType===g.eventType;
}var a=(function(){function g(h,j){var i=this;this.name=h;this.$callback=e.Callbacks("unique stopOnFalse");this._thisEventCallback=function(k){i.$callback.fire(k);
e(document).triggerHandler(i.name);};this.evts=new d(f);this.$callback.add(j);}Object.defineProperty(g.prototype,"Name",{get:function(){return this.name;
},enumerable:true,configurable:true});g.prototype.AddCallback=function(h){this.$callback.add(h);return this;};g.prototype.AddCallbacks=function(h){this.$callback.add(h);
return this;};g.prototype.RemoveCallback=function(h){this.$callback.remove(h);return this;};g.prototype.RemoveCallbacks=function(h){if(h){this.$callback.empty();
}else{this.$callback.remove(h);}return this;};g.prototype.AddTrigger=function(h){if(this.evts.has(h)){return false;}e(h.target).on(h.eventType,this._thisEventCallback);
this.evts.add(h);return true;};g.prototype.AddTriggers=function(i){for(var k=0,j=i;k<j.length;k++){var h=j[k];this.AddTrigger(h);}return this;};g.prototype.RemoveTrigger=function(h){if(!this.evts.has(h)){return false;
}e(h.target).off(h.eventType,this._thisEventCallback);return this.evts.del(h);};g.prototype.RemoveTriggers=function(i){if(!i){this.RemoveAllTriggers();
}for(var k=0,j=i;k<j.length;k++){var h=j[k];this.RemoveTrigger(h);}return this;};g.prototype.RemoveAllTriggers=function(){var h=this;this.evts.forEach(function(i){e(i.target).off(i.eventType,h._thisEventCallback);
});this.evts.clear();return this;};g.prototype.Dispose=function(){this.RemoveAllTriggers();this.$callback.disable();};return g;}());b.Event=a;});define("lib/preview/controller",["require","exports","lib/util/jquery/customEvent"],function(b,a,d){var c=(function(){function e(f){var g=this;
this.callback_onPreviewTriggerd=function(h){g.ReserveUpdate();};this.onPreviewTriggered=new d.Event("onPreviewTriggered",this.callback_onPreviewTriggerd);
this.model=f.model;this.view=f.view;this.model.onUpdated(function(h){g.view.Update(h);});}Object.defineProperty(e.prototype,"OnPreviewTriggerd",{get:function(){return this.onPreviewTriggered;
},enumerable:true,configurable:true});e.prototype.ReserveUpdate=function(){return this.model.ReserveUpdate(this.BuildUpdateArg());};e.prototype.Update=function(){this.model.Update(this.BuildUpdateArg());
return this;};e.prototype.Show=function(){if(!this.model.PreviewHTML){this.Update();}else{this.model.Show();}return this;};e.prototype.Hide=function(){this.model.Hide();
return this;};e.prototype.Enable=function(){this.model.SetAsEnabled();return this;};e.prototype.Disable=function(){this.model.SetAsDisabled();return this;
};e.prototype.Dispose=function(){this.model.Dispose();this.view.Dispose();this.onPreviewTriggered.Dispose();};return e;}());a.PreviewController=c;});define("lib/ss/preview/controller",["require","exports","jquery","lib/preview/controller"],function(c,a,e,b){var d=(function(g){__extends(f,g);
function f(h){g.call(this,h);this.textbox=h.textbox;this.OnPreviewTriggerd.AddTrigger({target:e(this.textbox),eventType:"keyup"});}f.prototype.BuildUpdateArg=function(h){var i=this.textbox.value;
return{source:i,extraArg:h};};return f;}(b.PreviewController));a.SSPreviewController=d;});define("lib/ss/preview/partyBBS/controller",["require","exports","jquery","lib/ss/preview/controller"],function(c,b,d,a){var e=(function(f){__extends(g,f);
function g(h){f.call(this,h);this.titleInput=h.titleInput;this.nameInput=h.nameInput;this.OnPreviewTriggerd.AddTriggers([{target:d(this.titleInput),eventType:"keyup"},{target:d(this.nameInput),eventType:"keyup"}]);
}g.prototype.BuildUpdateArg=function(j){var h=this.nameInput.value;var k=this.titleInput.value;var i=d.extend(j,{name:h,title:k});return f.prototype.BuildUpdateArg.call(this,{name:h,title:k});
};return g;}(a.SSPreviewController));b.PartyBBSController=e;});define("lib/ss/preview/controllers",["require","exports","lib/ss/preview/partyBBS/controller"],function(c,b,a){b.PartyBBS=a.PartyBBSController;
});define("lib/preview/package",["require","exports"],function(b,a){});define("lib/ss/preview/packagedPreview",["require","exports"],function(b,a){});define("lib/ss/preview/diary/package",["require","exports","jquery","lib/ss/preview/controller","lib/ss/preview/diary/model","lib/ss/preview/diary/view"],function(e,c,g,b,d,f){var a=(function(){function h(i){this._model=new d.DiaryModel(i.model);
this._view=new f.DiaryView(i.view.insert);var j=g.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new b.SSPreviewController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());c.DiaryPackage=a;});
define("lib/ss/preview/message/package",["require","exports","jquery","lib/preview/view","lib/ss/preview/controller","lib/ss/preview/message/model"],function(d,b,f,c,g,a){var e=(function(){function h(i){this._model=new a.MessageModel(i.model.profile);
this._view=new c.PreviewView(i.view.insert);var j=f.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new g.SSPreviewController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());b.MessagePackage=e;
});define("lib/ss/preview/partyBBS/package",["require","exports","jquery","lib/preview/view","lib/ss/preview/partyBBS/model","lib/ss/preview/partyBBS/controller"],function(e,c,f,b,a,g){var d=(function(){function h(i){this._model=new a.PartyBBSModel(i.model.profile);
this._view=new b.PreviewView(i.view.insert);var j=f.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new g.PartyBBSController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());c.PartyBBSPackage=d;
});define("lib/ss/preview/serif/package",["require","exports","jquery","lib/preview/view","lib/ss/preview/controller","lib/ss/preview/serif/model"],function(d,c,e,b,f,a){var g=(function(){function h(i){this._model=new a.SerifModel(i.model.profile);
this._view=new b.PreviewView(i.view.insert);var j=e.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new f.SSPreviewController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());c.SerifPackage=g;});
define("lib/ss/preview/packages",["require","exports","lib/ss/preview/diary/package","lib/ss/preview/message/package","lib/ss/preview/partyBBS/package","lib/ss/preview/serif/package"],function(e,c,f,d,b,a){c.Diary=f.DiaryPackage;
c.Message=d.MessagePackage;c.PartyBBS=b.PartyBBSPackage;c.Serif=a.SerifPackage;});define("lib/ss/preview",["require","exports","lib/ss/preview/models","lib/ss/preview/model_formatter","lib/ss/preview/views","lib/ss/preview/controllers","lib/ss/preview/packages","lib/ss/preview/config","lib/ss/profile"],function(d,f,c,i,a,e,g,b,h){f.Model=c;
f.Formatter=i;f.View=a;f.Controller=e;f.Package=g;f.Config=b;f.Profile=h;});define("lib/ss/pages/characterSettings",["require","exports"],function(c,a){var b=(function(){function d(){}d.ExtractIconUrlArray=function(){var e=[];
for(var g=6;;g+=3){var j=g<10?("0"+g):(""+g);var f=document.getElementsByName("ctl"+j);if(f.length===0){return e;}var h=(f[0]);e.push(h.value);}};d.ExtractNickname=function(){var e=document.getElementById("TextBox2");
if(e===null){return null;}return e.value;};return d;}());a.CharacterSettings=b;});define("lib/ss/pages",["require","exports","lib/ss/pages/characterSettings"],function(b,a,c){a.CharacterSettings=c.CharacterSettings;
});define("SSPreviewer.user",["require","exports","jquery","lib/ss/profile","lib/ss/page","lib/ss/preview","lib/ss/pages"],function(c,b,g,d,h,f,e){var a;
(function(i){function j(){f.Config.Preview.previewDelay_ms=100;f.Config.SSPreview.randomizesDiceTagResult=true;f.Config.SSPreview.randomizesCardTagResult=true;
function r(u,p){return p.toArray().map(function(w,v){return new f.Package.Serif({model:{profile:u},view:{insert:{target:w,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:w},});
});}function s(u,p){return p.toArray().map(function(w,v){var x=g(w).nextUntil("input").last().next()[0];return new f.Package.Message({model:{profile:u},view:{insert:{target:x,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:w},});
});}function n(p){return r(p,g("textarea"));}function m(p){return s(p,g("textarea"));}function q(v){for(var w=0,u=v;w<u.length;w++){var p=u[w];p.Controller.Update();
}}function o(u){for(var v=0,p=u;v<p.length;v++){var w=p[v];w.Controller.Hide();}}function t(u){if(u.length===0){return;}var p=g("<a id='showAllPreviews' class='clearFix' href='#' style='display: block; float: right;'><button type='button' onclick='return false;'>全てのプレビューを<span class='hideOnActive'>表示</span><span class='showOnActive'>隠す</span></button></a>").on("click",function(){p.toggleClass("active");
if(p.hasClass("active")){q(u);}else{o(u);}});g("td.BackMessage2").eq(0).prepend(p);}var k=h.PageConfig;var l=new d.Profile();k.ForAllPages=new h.Page(l,function(p){g("#char_Button").before("<center class='F1'>↓(Previewer) アイコン・愛称の自動読込↓</center>");
});k.MainPage=new h.Page(l,function(v){var w=[];var u=g("#Diary_TextBox")[0];if(u){var y=new f.Package.Diary({model:{profile:v},view:{insert:{target:u,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:u},});
w.push(y);}var p=g("input").filter("[style*='width:367px']");var x=r(v,p);if(x.length>0){Array.prototype.push.apply(w,x);}t(w);});k.PartyBBS=new h.Page(l,function(u){var p=g("#commentTxt");
if(p.length===0){return;}var v=new f.Package.PartyBBS({model:{profile:u},view:{insert:{target:p.closest("div.BackBoard")[0],way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:p[0],nameInput:g("#nameTxt")[0],titleInput:g("#titleTxt")[0]},});
t([v]);});k.Trade=new h.Page(l,function(p){var u=n(p);t(u);});k.Reinforcement=new h.Page(l,function(p){var u=n(p);t(u);});k.BattleSettings=new h.Page(l,function(p){var u=n(p);
t(u);});k.BattleWords=new h.Page(l,function(p){var u=n(p);t(u);});k.Message=new h.Page(l,function(p){var u=m(p);t(u);});k.GroupMessage=new h.Page(l,function(p){var u=m(p);
t(u);});k.MessageLog=new h.Page(l,function(p){var u=m(p);t(u);});k.CharacterSettings=new h.Page(l,function(p){p.SaveIconURLArray(e.CharacterSettings.ExtractIconUrlArray());
p.SaveNickname(e.CharacterSettings.ExtractNickname());});k.Community=new h.Page(l,function(u){var p=g("textarea")[0];if(!p){return;}var v=new f.Package.Diary({model:{profile:u,showsCharCounts:false},view:{insert:{target:p,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:p},});
t([v]);});k.RunInitializer(l,document.location);}j();})(a||(a={}));});(function(){require(["SSPreviewer.user"],function(){});GM_addStyle(GM_getResourceText("CSS_STYLE"));
})();