// ==UserScript==
// @name        SSPreviewer (beta)
// @namespace   11powder
// @author      pejuta
// @description 七海で色々なプレビューを表示する
// @include     /^http://www\.sssloxia\.jp/d/.*?(?:\.aspx)(?:\?.+)?$/
// @require     https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js
// @require     http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
// @version     0.1.023
// @grant       none
// ==/UserScript==
//
// !!!:第二回更新時に向けてのチェックリスト。現在は暫定的な仕様のため実際の動作と異なる可能性がある
// 日記/メッセージ/台詞の正確なフォーマット
// 改行の変更後の仕様を要確認。
var __extends=(this&&this.__extends)||function(f,a){for(var e in a){if(a.hasOwnProperty(e)){f[e]=a[e];}}function c(){this.constructor=f;}f.prototype=a===null?Object.create(a):(c.prototype=a.prototype,new c());
};define("lib/ss/profile",["require","exports"],function(c,a){var b=(function(){function d(e){if(e){this.iconURLArray=e.iconURLArray;this.nickname=e.nickname;
this.nameColor=e.nameColor;}else{this.iconURLArray=d.LoadIconURLArray();this.nickname=d.LoadNickname();this.nameColor=d.LoadNameColor();}}d.prototype.SaveIconURLArray=function(e){if(e!==undefined){this.iconURLArray=e;
}d.SaveIconURLArray(this.iconURLArray);return this;};d.prototype.SaveNickname=function(e){if(e!==undefined){this.nickname=e;}d.SaveNickname(this.nickname);
return this;};d.prototype.SaveNameColor=function(e){if(e!==undefined){this.nameColor=e;}d.SaveNameColor(this.nickname);return this;};d.LoadIconURLArray=function(){var e=localStorage.getItem("SSPreview_IconURLArray");
if(e===null){return[];}return JSON.parse(e);};d.SaveIconURLArray=function(e){localStorage.setItem("SSPreview_IconURLArray",JSON.stringify(e));};d.LoadNickname=function(){var e=localStorage.getItem("SSPreview_Nickname");
if(e===null){return"(名称)";}return e;};d.SaveNickname=function(e){localStorage.setItem("SSPreview_Nickname",e);};d.LoadNameColor=function(){var e=localStorage.getItem("SSPreview_NameColor");
if(e===null){return"";}return e;};d.SaveNameColor=function(e){localStorage.setItem("SSPreview_NameColor",e);};return d;}());a.Profile=b;});define("lib/ss/page",["require","exports"],function(b,a){var c=(function(){function e(f,g){this.profile=f;
this.initializer=g;}e.prototype.Init=function(f){this.initializer(f);};Object.defineProperty(e.prototype,"Settings",{get:function(){return this.profile;
},enumerable:true,configurable:true});Object.defineProperty(e.prototype,"Initializer",{get:function(){return this.initializer;},enumerable:true,configurable:true});
return e;}());a.Page=c;var d=(function(){function e(){}Object.defineProperty(e,"pathnameToPage",{get:function(){return{"/d/mainaction.aspx":e.MainPage,"/d/pbbs.aspx":e.PartyBBS,"/d/tradeaction.aspx":e.Trade,"/d/strgsaction.aspx":e.Reinforcement,"/d/battle.aspx":e.BattleSettings,"/d/battlemessage.aspx":e.BattleWords,"/d/battlemessageprc.aspx":e.BattleWords,"/d/bms.aspx":e.BattleWords,"/d/messageaction.aspx":e.Message,"/d/commesaction.aspx":e.GroupMessage,"/d/messagelog.aspx":e.MessageLog,"/d/commeslog.aspx":e.MessageLog,"/d/chara.aspx":e.CharacterSettings,"/d/com.aspx":e.Community,};
},enumerable:true,configurable:true});e.RunInitializer=function(g,f){if(this.ForAllPages){this.ForAllPages.Init(g);}var h=f.pathname;if(e.pathnameToPage.hasOwnProperty(h)&&e.pathnameToPage[h]){e.pathnameToPage[h].Init(g);
}};return e;}());a.PageConfig=d;});define("lib/util/string/format",["require","exports"],function(b,a){function c(g,e){if(g===null||g===undefined){return g;
}var f=""+g;for(var d in e){if(e[d]===undefined&&e[d]===null){continue;}f=f.replace(new RegExp("{"+d+"}","g"),""+e[d]);}return f;}return c;});define("lib/util/string/replaceLoop",["require","exports"],function(b,a){function c(f,d,g){if(f===null||f===undefined){return f;
}var e=""+f;if(typeof d==="string"){for(;;){if(e.indexOf(d)===-1){return e;}e=e.replace(d,g);}}for(;;){if(!d.test(e)){return e;}e=e.replace(d,g);}}return c;
});define("lib/util/html/escape",["require","exports"],function(b,e){var g={"&":"&amp;","'":"&#x27;","`":"&#x60;",'"':"&quot;","<":"&lt;",">":"&gt;"};var i=new RegExp("["+Object.keys(g).join("")+"]","g");
function l(k,n,m){if(k===undefined||k===null){return k;}if(n===undefined||n===null){return k.replace(i,function(o){return g[o];});}return k.replace(new RegExp(n,m),function(o){return l(o);
});}e.escape=l;var a={};for(var d=0,j=Object.keys(g);d<j.length;d++){var c=j[d];a[g[c]]=c;}var h=new RegExp("(?:"+Object.keys(a).join("|")+")","g");function f(k,n,m){if(k===undefined||k===null){return k;
}if(n===undefined||n===null){return k.replace(h,function(o){return a[o];});}return k.replace(new RegExp(l(n),m),function(o){return f(o);});}e.unescape=f;
});define("lib/util/html/tag",["require","exports"],function(b,a){function c(d){return d.replace(/(?:\r\n|\r|\n)/g,"<BR>");}a.lineBreaksToBR=c;});define("lib/ss/expr/parser",["require","exports"],function(b,a){var c=(function(h){__extends(g,h);
function g(){h.apply(this,arguments);}return g;}(Array));a.IGroupOr=c;var f=(function(g){__extends(h,g);function h(){g.apply(this,arguments);}return h;
}(Array));a.IGroupAnd=f;var d=(function(){function g(h){this.enableAt3Mode=h.enableAt3Mode;this.iconNumber=h.iconNumber;this.text=h.text;this.changedName=h.hasOwnProperty("changedName")?h.changedName:null;
}Object.defineProperty(g.prototype,"EnableAt3Mode",{get:function(){return this.enableAt3Mode;},enumerable:true,configurable:true});Object.defineProperty(g.prototype,"Text",{get:function(){return this.text;
},enumerable:true,configurable:true});Object.defineProperty(g.prototype,"IconNumber",{get:function(){return this.iconNumber;},enumerable:true,configurable:true});
Object.defineProperty(g.prototype,"ChangedName",{get:function(){return this.changedName;},enumerable:true,configurable:true});return g;}());var e=(function(){function g(){}g.Parse=function(i,m,w){var l=m?-1:0;
var x;if(w){x=i.split("###");}else{x=[i];}var n=[];for(var t=0,k=x.length;t<k;t++){var h=x[t].split(/(?:(@@@|@((?![^<@]*\/\d+\/)[^<@]+)@)(?:\/(\d+)\/)?|\/(\d+)\/)/g);
if(h.length===1){n.push([new d({enableAt3Mode:m,iconNumber:l,text:x[t]})]);continue;}var s=[];for(var q=0,o=h.length;q<o;q+=5){var v=h[q];if(q===0){if(v!==""){s.push(new d({enableAt3Mode:m,iconNumber:l,text:h[q]}));
}continue;}var p=null;var u=m;var r=void 0;if(h[q-4]===undefined){r=h[q-1];}else{if(h[q-4]==="@@@"){r=h[q-2];u=true;}else{r=h[q-2];p=h[q-3];u=false;}}var j=u?-1:0;
if(r!==undefined){j=parseInt(r);}s.push(new d({enableAt3Mode:u,changedName:p,iconNumber:j,text:v}));}n.push(s);}return n;};return g;}());a.Parser=e;});
define("lib/preview/model_formatter",["require","exports"],function(b,a){var c=(function(){function d(){}d.prototype.Exec=function(f,e){return f;};return d;
}());a.Formatter=c;});define("lib/ss/preview/templates",["require","exports"],function(b,a){var c;(function(d){d.Diary=null;d.DiaryCharCountsHTML=null;
d.Message=null;d.PartyBBS=null;d.Serif=null;})(c=a.Preview||(a.Preview={}));});define("lib/preview/config",["require","exports"],function(b,a){a.neverUpdateHTMLIfHidden=true;
a.previewDelay_ms=0;});define("lib/ss/preview/config",["require","exports","lib/ss/preview/templates","lib/preview/config"],function(b,a,c,d){a.Templates=c;
a.Preview=d;var e;(function(f){f.imgBaseURL=null;f.diary_showsCharCounts=true;f.randomizesDiceTagResult=false;f.diceTagTemplateHTML=null;})(e=a.SSPreview||(a.SSPreview={}));
});define("lib/ss/preview/model_formatter",["require","exports","lib/util/string/format","lib/util/string/replaceLoop","lib/util/html/escape","lib/util/html/tag","lib/ss/expr/parser","lib/ss/preview/config"],function(b,c,e,f,h,g,d,a){var i=(function(){function j(k){this.profile=k.profile;
this.at3ModeAsDefault=k.at3ModeAsDefault||false;this.allowsOrTag=k.allowsOrTag||false;this.template=k.template||Object.create(j._DEFAULT_TEMPLATE);this.separators=k.separators?{and:k.separators.and||j._DETAULT_SEPARATORS.and,or:k.separators.or||j._DETAULT_SEPARATORS.or}:Object.create(j._DETAULT_SEPARATORS);
}Object.defineProperty(j.prototype,"Profile",{get:function(){return this.profile;},enumerable:true,configurable:true});Object.defineProperty(j.prototype,"Templates",{get:function(){return this.template;
},enumerable:true,configurable:true});Object.defineProperty(j.prototype,"Separators",{get:function(){return this.separators;},enumerable:true,configurable:true});
Object.defineProperty(j.prototype,"At3ModeAsDefault",{get:function(){return this.at3ModeAsDefault;},enumerable:true,configurable:true});Object.defineProperty(j.prototype,"AllowsOrTag",{get:function(){return this.allowsOrTag;
},enumerable:true,configurable:true});j.GenerateDiceTag=function(k){if(k===void 0){k=false;}var l=1;if(k){l=Math.floor(Math.random()*6)+1;}return e(a.SSPreview.diceTagTemplateHTML||j._DEFAULT_DICE_TEMPLATE,{imgDir:a.SSPreview.imgBaseURL||j._DEFAULT_IMG_BASE_URL,resultNum:l});
};j.prototype.Exec=function(l){var k=h.escape(l);k=f(k,j.reReplace_EscapedDecoTag,"<span class='$1'>$2</span>");k=this.Format(d.Parser.Parse(k,this.at3ModeAsDefault,this.allowsOrTag));
k=k.replace(j.reReplace_EscapedDiceTag,function(m){return j.GenerateDiceTag(a.SSPreview.randomizesDiceTagResult);});k=g.lineBreaksToBR(k);k=h.unescape(k,"<BR>","g");
return k;};j.prototype.Format=function(k){var l=this;return k.map(function(o,n,m){return o.map(function(v,q,r){var t;if(v.EnableAt3Mode){if(v.IconNumber===-1){t=l.template.Body_At3Mode;
}else{t=l.template.Body_At3ModeAndIcon;}}else{t=l.template.Body;}var u="";if(v.IconNumber!==-1){u=l.profile.iconURLArray[v.IconNumber]||((a.SSPreview.imgBaseURL||j._DEFAULT_IMG_BASE_URL)+"default.jpg");
}var s=v.ChangedName===null?l.profile.nickname:v.ChangedName;var p=v.Text;return e(t,{iconURL:u,name:s,nameColor:l.profile.nameColor,bodyHTML:p});}).join(l.separators.and);
}).join(this.separators.or);};j._DEFAULT_TEMPLATE={Body:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon" rowspan="2"><IMG border = 0 alt=Icon align=left src="{iconURL}" width=60 height=60></td><td class="Name"><font color="{nameColor}" class="B">{name}</font></td></tr><tr><td class="Words">\u300C{bodyHTML}\u300D</td></tr></table>',Body_At3ModeAndIcon:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon"><IMG border = 0 alt=Icon align=left src="{iconURL}" width=60 height=60></td><td class="String">{bodyHTML}</td></tr></table>',Body_At3Mode:'<table class="WordsTable" CELLSPACING=0 CELLPADDING=0><tr><td class="Icon"/><td class="String">{bodyHTML}</td></tr></table>'};
j._DEFAULT_DICE_TEMPLATE='<img alt="dice" src="{imgDir}d{resultNum}.png" border="0" height="20" width="20">';j._DEFAULT_IMG_BASE_URL="http://www.sssloxia.jp/p/";
j._DETAULT_SEPARATORS={and:"",or:"<div class='separator_or'/>"};j.reReplace_EscapedDecoTag=new RegExp(h.escape("<(F[1-7]|B|I|S)>([\\s\\S]*?)</\\1>"),"g");
j.reReplace_EscapedDiceTag=new RegExp(h.escape("<D>"),"g");return j;}());c.Formatter=i;});define("lib/interface/disposable",["require","exports"],function(b,a){});
define("lib/util/timer/timer",["require","exports"],function(b,a){var c=(function(){function d(){this.date_start=0;this.time_ms=0;this.resetTimeWhenStarting=false;
}Object.defineProperty(d.prototype,"Time_ms",{get:function(){return this.time_ms+Date.now()-this.date_start;},enumerable:true,configurable:true});Object.defineProperty(d.prototype,"isRunning",{get:function(){return !!this.date_start;
},enumerable:true,configurable:true});d.prototype.Start=function(){if(this.isRunning&&!this.resetTimeWhenStarting){return;}if(this.resetTimeWhenStarting){this.ResetTime();
}this.date_start=Date.now();return this;};d.prototype.Stop=function(){return this.Pause().ResetTime();};d.prototype.Pause=function(){if(!this.isRunning){return;
}this.time_ms+=Date.now()-this.date_start;this.date_start=0;return this;};d.prototype.ResetTime=function(){if(this.isRunning){this.date_start=Date.now();
}else{this.date_start=0;}this.time_ms=0;return this;};d.prototype.PrintTime=function(){console.log("time(ms): "+this.Time_ms);return this;};return d;}());
return c;});define("lib/util/timer/timerEvent",["require","exports","lib/util/timer/timer"],function(b,a,c){var d=(function(e){__extends(f,e);function f(g,h){e.call(this);
this.afterPeriod=g;this.period_ms=h;this.id=0;}f.prototype.setCallbackArg=function(g){if(g===undefined){return;}this.callbackArg=g;};f.prototype.Start=function(h){this.setCallbackArg(h);
if(!this.isRunning){var g=this.period_ms-this.time_ms;if(g<0){g=0;}this.id=setTimeout(this.afterPeriod,g,h);}e.prototype.Start.call(this);return this;};
f.prototype.Stop=function(g,h){if(g===void 0){g=false;}if(g){this.setCallbackArg(h);this.afterPeriod((h===undefined?this.callbackArg:h));}return this.Pause().ResetTime();
};f.prototype.Pause=function(){if(!this.isRunning){return;}clearTimeout(this.id);this.id=0;e.prototype.Pause.call(this);return this;};f.prototype.ResetTime=function(g){this.setCallbackArg(g);
if(this.isRunning){clearTimeout(this.id);this.id=setTimeout(this.afterPeriod,this.period_ms,(g===undefined?this.callbackArg:g));}e.prototype.ResetTime.call(this);
return this;};f.prototype.Dispose=function(){this.Stop();};return f;}(c));return d;});define("lib/preview/model",["require","exports","jquery","lib/preview/model_formatter","lib/util/timer/timerEvent","lib/preview/config"],function(d,c,f,e,g,a){var b=(function(){function h(i,j){if(i===void 0){i=new e.Formatter();
}if(j===void 0){j=a.previewDelay_ms;}this.formatter=i;this.delay_ms=j;this.previewHTML=null;this.source=null;this.extraArg=null;this.isVisible=false;this.isDisabled=false;
this.$onUpdated=f.Callbacks("stopOnFalse");this.InitTimerEvent();}Object.defineProperty(h.prototype,"PreviewHTML",{get:function(){return this.previewHTML;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"Delay_ms",{get:function(){return this.delay_ms;},set:function(i){this.delay_ms=i;
this.InitTimerEvent();},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"IsVisible",{get:function(){return this.isVisible;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"IsDisabled",{get:function(){return this.isDisabled;},enumerable:true,configurable:true});h.prototype.ReserveUpdate=function(i){if(this.isDisabled){return false;
}if(i.source===this.source&&JSON.stringify(i.extraArg)===JSON.stringify(this.extraArg)){return false;}this.timerEvt.Start(i);return true;};h.prototype.InitTimerEvent=function(){var i=this;
if(this.timerEvt){this.timerEvt.Dispose();}this.timerEvt=new g(function(j){i.Update(j);},this.delay_ms);this.timerEvt.resetTimeWhenStarting=true;return this;
};h.prototype.Update=function(i){this.InitOnUpdating().UpdateInfo(i);this.TriggerOnUpdatedEvent();return this;};h.prototype.InitOnUpdating=function(){this.SetAsShown();
return this;};h.prototype.UpdateInfo=function(i){if(this.isDisabled){return false;}if(!this.isVisible&&a.neverUpdateHTMLIfHidden){return false;}this.source=i.source;
this.extraArg=i.extraArg;this.previewHTML=this.formatter.Exec(i.source,i.extraArg);return true;};h.prototype.Show=function(){this.SetAsShown();if(!this.previewHTML){return this;
}this.TriggerOnUpdatedEvent();return this;};h.prototype.Hide=function(){this.SetAsHidden();if(!this.previewHTML){return this;}this.TriggerOnUpdatedEvent();
return this;};h.prototype.SetAsHidden=function(){this.isVisible=false;return this;};h.prototype.SetAsShown=function(){this.isVisible=true;return this;};
h.prototype.SetAsDisabled=function(){this.isDisabled=true;return this;};h.prototype.SetAsEnabled=function(){this.isDisabled=false;return this;};h.prototype.TriggerOnUpdatedEvent=function(){this.$onUpdated.fire(this);
return this;};h.prototype.onUpdated=function(i){if(i instanceof Array){this.$onUpdated.add(i);}else{this.$onUpdated.add(i);}return this;};h.prototype.offUpdated=function(i){if(i instanceof Array){this.$onUpdated.remove(i);
}else{this.$onUpdated.remove(i);}return this;};h.prototype.Dispose=function(){this.timerEvt.Dispose();this.$onUpdated.disable();this.previewHTML=null;this.isDisabled=true;
this.isVisible=false;};return h;}());c.PreviewModel=b;});define("lib/ss/preview/model",["require","exports","lib/preview/model"],function(b,a,d){var c=(function(f){__extends(e,f);
function e(g,h){f.call(this,g,h);}e.prototype.UpdateInfo=function(g){if(g.source===""){this.SetAsHidden();}return f.prototype.UpdateInfo.call(this,g);};
return e;}(d.PreviewModel));a.SSPreviewModel=c;});define("lib/ss/preview/partyBBS/model_formatter",["require","exports","lib/util/string/format","lib/ss/preview/model_formatter"],function(c,a,e,b){var d=(function(g){__extends(f,g);
function f(h){g.call(this,h);}f.prototype.Exec=function(k,j){if(j===void 0){j={title:"",name:""};}var h=g.prototype.Exec.call(this,k);if(j.title===""){j=Object.create(j);
j.title="無題";}var i=e(f.TEMPLATE_CONTAINER,j);return e(i,{html:h});};f.TEMPLATE_CONTAINER='<div class="BackBoard">\n    <b>xxx \uFF1A{title}</b> &nbsp;&nbsp;{name}&#12288;\uFF0820xx/xx/xx xx:xx:xx\uFF09 <br> <br>{html}<br><br><br clear="ALL">\n</div>';
return f;}(b.Formatter));a.PartyBBSFormatter=d;});define("lib/ss/preview/partyBBS/model",["require","exports","lib/ss/preview/model","lib/ss/preview/partyBBS/model_formatter","lib/ss/preview/templates"],function(d,c,f,b,e){var a=(function(h){__extends(g,h);
function g(i,j){h.call(this,new b.PartyBBSFormatter({profile:i,template:e.Preview.PartyBBS,at3ModeAsDefault:true}),j);}g.prototype.ReserveUpdate=function(i){if(i.source===this.source&&i.extraArg.title===this.extraArg.title&&i.extraArg.name===this.extraArg.name){return false;
}return h.prototype.ReserveUpdate.call(this,i);};g.prototype.UpdateInfo=function(i){if(i.extraArg.name===""){this.SetAsHidden();}return h.prototype.UpdateInfo.call(this,i);
};return g;}(f.SSPreviewModel));c.PartyBBSModel=a;});define("lib/ss/preview/diary/model_formatter",["require","exports","lib/util/string/format","lib/ss/preview/model_formatter"],function(c,b,e,a){var d=(function(g){__extends(f,g);
function f(h){g.call(this,h);}f.prototype.Exec=function(i){var h=g.prototype.Exec.call(this,i);return e(f.TEMPLATE_CONTAINER,{html:h});};f.TEMPLATE_CONTAINER='<div name="Diary">{html}</div>';
return f;}(a.Formatter));b.DiaryFormatter=d;});define("lib/ss/expr/rule",["require","exports"],function(c,b){function a(e){var f=e.length-e.replace(/\n/g,"").length;
var d=e.length-f;return{charCount:d,lfCount:f};}b.CountExprChars=a;});define("lib/ss/preview/diary/model",["require","exports","lib/ss/preview/diary/model_formatter","lib/ss/preview/model","lib/ss/expr/rule","lib/ss/preview/config","lib/ss/preview/templates"],function(e,d,b,g,c,a,f){var h=(function(j){__extends(i,j);
function i(k){j.call(this,new b.DiaryFormatter({profile:k.profile,template:f.Preview.Diary,at3ModeAsDefault:true}),k.delay_ms);if("showsCharCounts" in k){this.showsCharCounts=k.showsCharCounts;
}else{this.showsCharCounts=a.SSPreview.diary_showsCharCounts||false;}}Object.defineProperty(i.prototype,"ShowsCharCounts",{get:function(){return this.showsCharCounts;
},enumerable:true,configurable:true});Object.defineProperty(i.prototype,"CharCounts",{get:function(){return this.charCounts;},enumerable:true,configurable:true});
i.prototype.UpdateInfo=function(k){this.charCounts=c.CountExprChars(k.source);return j.prototype.UpdateInfo.call(this,k);};i.MAX_LENGTH_OF_CHARS=5000;i.MAX_COUNT_OF_LFS=2500;
return i;}(g.SSPreviewModel));d.DiaryModel=h;});define("lib/ss/preview/serif/model",["require","exports","lib/ss/preview/model_formatter","lib/ss/preview/model","lib/ss/preview/templates"],function(c,a,f,b,d){var e=(function(g){__extends(h,g);
function h(i,j){g.call(this,new f.Formatter({profile:i,template:d.Preview.Serif,allowsOrTag:true}),j);}return h;}(b.SSPreviewModel));a.SerifModel=e;});
define("lib/ss/preview/message/model",["require","exports","lib/ss/preview/model_formatter","lib/ss/preview/model","lib/ss/preview/templates"],function(c,b,f,a,d){var e=(function(g){__extends(h,g);
function h(i,j){g.call(this,new f.Formatter({profile:i,template:d.Preview.Message}),j);}return h;}(a.SSPreviewModel));b.MessageModel=e;});define("lib/ss/preview/model_formatters",["require","exports","lib/ss/preview/diary/model_formatter","lib/ss/preview/partyBBS/model_formatter","lib/ss/preview/model_formatter"],function(b,a,e,d,c){a.Diary=e.DiaryFormatter;
a.PartyBBS=d.PartyBBSFormatter;a.Formatter=c.Formatter;});define("lib/ss/preview/models",["require","exports","lib/ss/preview/partyBBS/model","lib/ss/preview/diary/model","lib/ss/preview/serif/model","lib/ss/preview/message/model"],function(d,c,b,a,f,e){c.PartyBBS=b.PartyBBSModel;
c.Diary=a.DiaryModel;c.Serif=f.SerifModel;c.Message=e.MessageModel;});define("lib/preview/view",["require","exports","jquery","lib/preview/config"],function(d,c,f,a){(function(g){g[g.InsertAfter=0]="InsertAfter";
g[g.InsertBefore=1]="InsertBefore";g[g.AppendTo=2]="AppendTo";g[g.PrependTo=3]="PrependTo";})(c.InsertWay||(c.InsertWay={}));var e=c.InsertWay;var b=(function(){function g(h){this.insert=h;
}Object.defineProperty(g.prototype,"PreviewContainer",{get:function(){return this.$container?this.$container[0]:null;},enumerable:true,configurable:true});
g.prototype.InsertContainer=function(){this.$container=f(g.containerHTML);switch(this.insert.way){case e.InsertAfter:this.$container.insertAfter(this.insert.target);
break;case e.InsertBefore:this.$container.insertBefore(this.insert.target);break;case e.AppendTo:this.$container.appendTo(this.insert.target);break;case e.PrependTo:this.$container.prependTo(this.insert.target);
break;default:throw new Error("InsertionMode指定エラー");}return this;};g.prototype.Hide=function(h){if(!this.$container){return;}this.$container.css("display","none");
return this;};g.prototype.Show=function(h){if(!this.$container){return;}this.$container.css("display","");return this;};g.prototype.Update=function(h){if(!this.$container){this.InsertContainer();
}if(h.IsVisible){this.Show(h);}else{this.Hide(h);if(a.neverUpdateHTMLIfHidden){return false;}}if(h.IsDisabled){return false;}this.$container.html(h.PreviewHTML);
return true;};g.prototype.Dispose=function(){this.$container.remove();};g.containerHTML='<div class="preview"/>';return g;}());c.PreviewView=b;});define("lib/ss/preview/diary/view",["require","exports","lib/util/string/format","lib/ss/preview/diary/model","lib/preview/view","lib/ss/preview/templates"],function(b,a,g,d,e,c){var f=(function(h){__extends(i,h);
function i(j){h.call(this,j);}i.BuildCharCountLine=function(l){var k=c.Preview.DiaryCharCountsHTML||i._DEFAULT_TEMPLATE_CHARCOUNTS;k=g(k,{charCount:l.charCount,charCountMax:d.DiaryModel.MAX_LENGTH_OF_CHARS,lfCount:l.lfCount,lfCountMax:d.DiaryModel.MAX_COUNT_OF_LFS});
var j=$(k);if(l.charCount>d.DiaryModel.MAX_LENGTH_OF_CHARS){j.children("[name=charCount]").addClass("over");}if(l.lfCount>d.DiaryModel.MAX_COUNT_OF_LFS){j.children("[name=lfCount]").addClass("over");
}return j;};i.prototype.Update=function(j){if(!h.prototype.Update.call(this,j)){return false;}if(j.ShowsCharCounts){this.$container.prepend(i.BuildCharCountLine(j.CharCounts));
}return true;};i._DEFAULT_TEMPLATE_CHARCOUNTS='<p class="char_count_line"><span class="char_count_cnt"><span name="charCount" class="char_count">{charCount}</span> / {charCountMax}</span> <span class="lf_count_cnt">(\u6539\u884C: <span name="lfCount" class="lf_count">{lfCount}</span> / {lfCountMax})</span></p>';
return i;}(e.PreviewView));a.DiaryView=f;});define("lib/ss/preview/views",["require","exports","lib/ss/preview/diary/view","lib/preview/view"],function(b,a,d,c){a.Diary=d.DiaryView;
a.InsertWay=c.InsertWay;});define("lib/util/array/set",["require","exports"],function(b,a){var c=(function(){function d(e,f){if(e===void 0){e=function(h,g){return(h===g);
};}this.equalityValidator=e;if(f&&f instanceof Array){this.innerArray=f.concat();}else{this.innerArray=[];}}d.prototype.has=function(f){return this.indexOf(f)!==-1;
};d.prototype.indexOf=function(h){var i=this;var f;var g=this.innerArray.some(function(j,k,e){f=k;return i.equalityValidator(j,h);});if(g){return f;}else{return -1;
}};d.prototype.add=function(f){if(this.has(f)){return this;}this.innerArray.push(f);return this;};d.prototype.addAll=function(f){for(var h=0,g=f;h<g.length;
h++){var i=g[h];this.add(i);}return this;};d.prototype.del=function(g){var f=this.indexOf(g);if(f===-1){return false;}this.innerArray.splice(f,1);return true;
};d.prototype.delAll=function(g){var j=false;for(var i=0,h=g;i<h.length;i++){var k=h[i];j=this.del(k)||j;}return j;};d.prototype.clear=function(){this.innerArray=[];
};d.prototype.forEach=function(h){for(var g=0,f=this.innerArray;g<f.length;g++){var e=f[g];h(e,e,this);}};Object.defineProperty(d.prototype,"size",{get:function(){return this.innerArray.length;
},enumerable:true,configurable:true});d.prototype.toArray=function(){return this.innerArray.concat();};return d;}());return c;});define("lib/util/jquery/customEvent",["require","exports","lib/util/array/set","jquery"],function(c,b,d,e){function f(h,g){return h.target.is(g)&&h.eventType===g.eventType;
}var a=(function(){function g(h,j){var i=this;this.name=h;this.$callback=e.Callbacks("unique stopOnFalse");this._thisEventCallback=function(k){i.$callback.fire(k);
e(document).triggerHandler(i.name);};this.evts=new d(f);this.$callback.add(j);}Object.defineProperty(g.prototype,"Name",{get:function(){return this.name;
},enumerable:true,configurable:true});g.prototype.AddCallback=function(h){this.$callback.add(h);return this;};g.prototype.AddCallbacks=function(h){this.$callback.add(h);
return this;};g.prototype.RemoveCallback=function(h){this.$callback.remove(h);return this;};g.prototype.RemoveCallbacks=function(h){if(h){this.$callback.empty();
}else{this.$callback.remove(h);}return this;};g.prototype.AddTrigger=function(h){if(this.evts.has(h)){return false;}e(h.target).on(h.eventType,this._thisEventCallback);
this.evts.add(h);return true;};g.prototype.AddTriggers=function(i){for(var k=0,j=i;k<j.length;k++){var h=j[k];this.AddTrigger(h);}return this;};g.prototype.RemoveTrigger=function(h){if(!this.evts.has(h)){return false;
}e(h.target).off(h.eventType,this._thisEventCallback);return this.evts.del(h);};g.prototype.RemoveTriggers=function(i){if(!i){this.RemoveAllTriggers();
}for(var k=0,j=i;k<j.length;k++){var h=j[k];this.RemoveTrigger(h);}return this;};g.prototype.RemoveAllTriggers=function(){var h=this;this.evts.forEach(function(i){e(i.target).off(i.eventType,h._thisEventCallback);
});this.evts.clear();return this;};g.prototype.Dispose=function(){this.RemoveAllTriggers();this.$callback.disable();};return g;}());b.Event=a;});define("lib/preview/controller",["require","exports","lib/util/jquery/customEvent"],function(b,a,d){var c=(function(){function e(f){var g=this;
this.callback_onPreviewTriggerd=function(h){g.ReserveUpdate();};this.onPreviewTriggered=new d.Event("onPreviewTriggered",this.callback_onPreviewTriggerd);
this.model=f.model;this.view=f.view;this.model.onUpdated(function(h){g.view.Update(h);});}Object.defineProperty(e.prototype,"OnPreviewTriggerd",{get:function(){return this.onPreviewTriggered;
},enumerable:true,configurable:true});e.prototype.ReserveUpdate=function(){return this.model.ReserveUpdate(this.BuildUpdateArg());};e.prototype.Update=function(){this.model.Update(this.BuildUpdateArg());
return this;};e.prototype.Show=function(){if(!this.model.PreviewHTML){this.Update();}else{this.model.Show();}return this;};e.prototype.Hide=function(){this.model.Hide();
return this;};e.prototype.Enable=function(){this.model.SetAsEnabled();return this;};e.prototype.Disable=function(){this.model.SetAsDisabled();return this;
};e.prototype.Dispose=function(){this.model.Dispose();this.view.Dispose();this.onPreviewTriggered.Dispose();};return e;}());a.PreviewController=c;});define("lib/ss/preview/controller",["require","exports","jquery","lib/preview/controller"],function(c,a,e,b){var d=(function(g){__extends(f,g);
function f(h){g.call(this,h);this.textbox=h.textbox;this.OnPreviewTriggerd.AddTrigger({target:e(this.textbox),eventType:"keyup"});}f.prototype.BuildUpdateArg=function(h){var i=this.textbox.value;
return{source:i,extraArg:h};};return f;}(b.PreviewController));a.SSPreviewController=d;});define("lib/ss/preview/partyBBS/controller",["require","exports","jquery","lib/ss/preview/controller"],function(c,b,d,a){var e=(function(f){__extends(g,f);
function g(h){f.call(this,h);this.titleInput=h.titleInput;this.nameInput=h.nameInput;this.OnPreviewTriggerd.AddTriggers([{target:d(this.titleInput),eventType:"keyup"},{target:d(this.nameInput),eventType:"keyup"}]);
}g.prototype.BuildUpdateArg=function(j){var h=this.nameInput.value;var k=this.titleInput.value;var i=d.extend(j,{name:h,title:k});return f.prototype.BuildUpdateArg.call(this,{name:h,title:k});
};return g;}(a.SSPreviewController));b.PartyBBSController=e;});define("lib/ss/preview/controllers",["require","exports","lib/ss/preview/partyBBS/controller"],function(c,b,a){b.PartyBBS=a.PartyBBSController;
});define("lib/ss/preview/packagedPreview",["require","exports"],function(b,a){});define("lib/ss/preview/diary/package",["require","exports","jquery","lib/ss/preview/controller","lib/ss/preview/diary/model","lib/ss/preview/diary/view"],function(e,c,g,b,d,f){var a=(function(){function h(i){this._model=new d.DiaryModel(i.model);
this._view=new f.DiaryView(i.view.insert);var j=g.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new b.SSPreviewController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());c.DiaryPackage=a;});
define("lib/ss/preview/message/package",["require","exports","jquery","lib/preview/view","lib/ss/preview/controller","lib/ss/preview/message/model"],function(d,b,f,c,g,a){var e=(function(){function h(i){this._model=new a.MessageModel(i.model.profile);
this._view=new c.PreviewView(i.view.insert);var j=f.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new g.SSPreviewController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());b.MessagePackage=e;
});define("lib/ss/preview/partyBBS/package",["require","exports","jquery","lib/preview/view","lib/ss/preview/partyBBS/model","lib/ss/preview/partyBBS/controller"],function(e,c,f,b,a,g){var d=(function(){function h(i){this._model=new a.PartyBBSModel(i.model.profile);
this._view=new b.PreviewView(i.view.insert);var j=f.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new g.PartyBBSController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());c.PartyBBSPackage=d;
});define("lib/ss/preview/serif/package",["require","exports","jquery","lib/preview/view","lib/ss/preview/controller","lib/ss/preview/serif/model"],function(d,c,e,b,f,a){var g=(function(){function h(i){this._model=new a.SerifModel(i.model.profile);
this._view=new b.PreviewView(i.view.insert);var j=e.extend(i.ctrl,{model:this._model,view:this._view});this._ctrl=new f.SSPreviewController(j);}Object.defineProperty(h.prototype,"Model",{get:function(){return this._model;
},enumerable:true,configurable:true});Object.defineProperty(h.prototype,"View",{get:function(){return this._view;},enumerable:true,configurable:true});
Object.defineProperty(h.prototype,"Controller",{get:function(){return this._ctrl;},enumerable:true,configurable:true});return h;}());c.SerifPackage=g;});
define("lib/ss/preview/packages",["require","exports","lib/ss/preview/diary/package","lib/ss/preview/message/package","lib/ss/preview/partyBBS/package","lib/ss/preview/serif/package"],function(e,c,f,d,b,a){c.Diary=f.DiaryPackage;
c.Message=d.MessagePackage;c.PartyBBS=b.PartyBBSPackage;c.Serif=a.SerifPackage;});define("lib/ss/preview",["require","exports","lib/ss/preview/models","lib/ss/preview/views","lib/ss/preview/controllers","lib/ss/preview/packages","lib/ss/preview/config","lib/ss/profile"],function(d,b,g,f,e,h,a,c){b.Model=g;
b.View=f;b.Controller=e;b.Package=h;b.Config=a;b.Profile=c;});define("lib/ss/pages/characterSettings",["require","exports"],function(c,a){var b=(function(){function d(){}d.ExtractIconUrlArray=function(){var e=[];
for(var g=4;;g+=3){var j=g<10?("0"+g):(""+g);var f=document.getElementsByName("ctl"+j);if(f.length===0){return e;}var h=(f[0]);e.push(h.value);}};d.ExtractNickname=function(){var e=document.getElementById("TextBox2");
if(e===null){return null;}return e.value;};return d;}());a.CharacterSettings=b;});define("lib/ss/pages",["require","exports","lib/ss/pages/characterSettings"],function(b,a,c){a.CharacterSettings=c.CharacterSettings;
});define("SSPreviewer.user",["require","exports","jquery","lib/ss/profile","lib/ss/page","lib/ss/preview","lib/ss/pages"],function(c,b,g,d,h,f,e){var a;
(function(i){function j(){f.Config.Preview.previewDelay_ms=100;f.Config.SSPreview.randomizesDiceTagResult=true;g("head").append('<style type=\'text/css\'>\n    .clearfix:after {\n        content: "";\n        display: block;\n        clear: both;\n    }\n    .separator_or {\n        background-color: rgba(255,255,255,0.25);\n        border-radius: 2px;\n        margin: 4px 0px;\n        text-align: center;\n        vertical-align: middle;\n    }\n    .separator_or:before {\n        content: "- OR -";\n    }\n</style>');
function r(u,p){return p.toArray().map(function(w,v){return new f.Package.Serif({model:{profile:u},view:{insert:{target:w,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:w},});
});}function s(u,p){return p.toArray().map(function(w,v){var x=g(w).nextUntil("input").last().next()[0];return new f.Package.Message({model:{profile:u},view:{insert:{target:w,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:w},});
});}function n(p){return r(p,g("textarea"));}function m(p){return s(p,g("textarea"));}function q(v){for(var w=0,u=v;w<u.length;w++){var p=u[w];p.Controller.Update();
}}function o(u){for(var v=0,p=u;v<p.length;v++){var w=p[v];w.Controller.Hide();}}function t(u){if(u.length===0){return;}g("head").append("<style type='text/css'>\n        .showOnActive, .active .hideOnActive {\n            display: none;\n        }\n        .active .showOnActive, .hideOnActive {\n            display: inherit;\n        }\n    </style>");
var p=g("<a id='showAllPreviews' class='clearFix' href='#' style='display: block; float: right;'><button type='button' onclick='return false;'>全てのプレビューを<span class='hideOnActive'>表示</span><span class='showOnActive'>隠す</span></button></a>").on("click",function(){p.toggleClass("active");
if(p.hasClass("active")){q(u);}else{o(u);}});g("td.BackMessage2").eq(0).prepend(p);}var k=h.PageConfig;var l=new d.Profile();k.ForAllPages=new h.Page(l,function(p){g("#char_Button").before("<center class='F1'>↓(Previewer) アイコン・愛称の自動読込↓</center>");
});k.MainPage=new h.Page(l,function(v){g("head").append("<style type='text/css'>\n    .char_count_line {\n        text-align: left;\n    }\n    .char_count_cnt {\n        font-size: 12px;\n    }\n    .lf_count_cnt {\n        font-size: 10px;\n    }\n    .char_count_line .char_count_over, .char_count_line .lf_count_over {\n        color: #CC3333;\n        font-weight: bold;\n    }\n    .char_count_line .char_count_over {\n        font-size: 16px;\n    }\n    .char_count_line .lf_count_over {\n        font-size: 14px;\n    }\n</style>");
var w=[];var u=g("#Diary_TextBox")[0];if(u){var y=new f.Package.Diary({model:{profile:v},view:{insert:{target:u,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:u},});
w.push(y);}var p=g("input").filter("[style*='width:367px']");var x=r(v,p);if(x.length>0){Array.prototype.push.apply(w,x);}t(w);});k.PartyBBS=new h.Page(l,function(u){var p=g("#commentTxt");
if(p.length===0){return;}var v=new f.Package.PartyBBS({model:{profile:u},view:{insert:{target:p.closest("div.BackBoard")[0],way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:p[0],nameInput:g("#nameTxt")[0],titleInput:g("#titleTxt")[0]},});
t([v]);});k.Trade=new h.Page(l,function(p){var u=n(p);t(u);});k.Reinforcement=new h.Page(l,function(p){var u=n(p);t(u);});k.BattleSettings=new h.Page(l,function(p){var u=n(p);
t(u);});k.BattleWords=new h.Page(l,function(p){var u=n(p);t(u);});k.Message=new h.Page(l,function(p){var u=m(p);t(u);});k.GroupMessage=new h.Page(l,function(p){var u=m(p);
t(u);});k.MessageLog=new h.Page(l,function(p){var u=m(p);t(u);});k.CharacterSettings=new h.Page(l,function(p){p.SaveIconURLArray(e.CharacterSettings.ExtractIconUrlArray());
p.SaveNickname(e.CharacterSettings.ExtractNickname());});k.Community=new h.Page(l,function(u){var p=g("textarea")[0];if(!p){return;}var v=new f.Package.Diary({model:{profile:u,showsCharCounts:false},view:{insert:{target:p,way:f.View.InsertWay.InsertAfter}},ctrl:{textbox:p},});
t([v]);});k.RunInitializer(l,document.location);}j();})(a||(a={}));});(function(){require(["SSPreviewer.user"],function(){});})();